function varargout = GABABseed_error(cluster_flag, compile_flag)

if nargin < 2, compile_flag = []; end
if isempty(compile_flag), compile_flag = 0; end
if nargin < 1, cluster_flag = []; end
if isempty(cluster_flag), cluster_flag = 1; end

%% Defining sim_spec.

sim_spec = struct();

i=1;
sim_spec.populations(i).name = 'RS';
sim_spec.populations(i).size = 1;
sim_spec.populations(i).equations = {['V''=@current/Cm; V(0)=' num2str(-65) '; monitor functions; monitor V.spikes(0);']};
sim_spec.populations(i).mechanism_list = {'IBiNaF','IBiKDR',...
%     'iPeriodicPulsesFacilitate'...
%     'IBdbiPoissonExpJason','itonicPaired','IBnoise',...
%     'IBiMMich','IBiCaH','IBleaknoisy',...
    };
sim_spec.populations(i).parameters = {'V_IC', -65, 'Cm', 0.9};
% sim_spec.populations(i).parameters = {...
%     'V_IC',-65,'IC_noise',0.25,'Cm',0.9, 'E_l',-67,'E_l_std',0,'g_l',0.1,...
%     'PPstim', 0, 'PPfreq', 4, 'PPwidth', 2, 'PPshift', 0, 'PPonset', 10,...
%     'PPoffset', 3000, 'ap_pulse_num', 0, 'ap_pulse_delay', 0, 'pulse_train_preset', 0,...
%     'kernel_type', 2, 'width2_rise', 0.75, 'PPFacTau', 200, 'PPFacFactor', 1,...
%     'gRAN', 0.005, 'ERAN', 0, 'tauRAN', 2, 'lambda', 1000,...
%     'stim', 5, 'onset', 0, 'offset', 0, 'stim2', 0, 'onset2', 0, 'offset2', Inf,...
%     'V_noise', 0.3,...
%     'gNaF', 100, 'E_NaF', 50,...
%     'gKDR', 80, 'E_KDR', -95,...
%     'gM', 0.5, 'E_M', -95,...
%     'gCaH', 0, 'E_CaH', 125,...
%     };

i=i+1;
sim_spec.populations(i).name = 'NG';
sim_spec.populations(i).size = 5;
sim_spec.populations(i).equations = {['V''=@current/Cm; V(0)=' num2str(-65) ]};
sim_spec.populations(i).mechanism_list = {'FSiNaF','FSiKDR',... 'IBleak','iAhuguenard',...
    %'iPeriodicPulsesFacilitate',...
    %'itonicPaired','IBnoise',...
    %'iPeriodicSpikes'
    };
sim_spec.populations(i).parameters = {'V_IC',-65,'Cm',0.9};
    %'V_IC',-65,'IC_noise',0.25,'Cm',0.9,...
    %'E_l',-67,'g_l',0.1,...
    %'PPstim',NGPPstim,'PPfreq',PPfreq,'PPwidth',PPwidth,'PPshift',PPshift,...
    %'PPonset',PPonset,'PPoffset',PPoffset,'ap_pulse_num',ap_pulse_num,...
    %'ap_pulse_delay',ap_pulse_delay,'pulse_train_preset',pulse_train_preset,...
    %'kernel_type',kernel_type,'width2_rise', width2_rise,'PPFacTau',PPFacTau,'PPFacFactor',PPFacFactor,...
    %'stim',3,'onset',0,'offset',50,'stim2',1,'onset2',50,'offset2',Inf,...
    %'V_noise',3,...
    %'gNaF',100,'E_NaF',50,...
    %'gKDR',80,'E_KDR',-95,...
    %'gA',20,'E_A',-95,...
    %'gSpike', 0, 'Sfreq', 7, 'tau_d', 125, 'tau_r', 15,...
    %};

i=1;
    sim_spec.connections(i).direction = 'NG->RS';                  
    sim_spec.connections(i).mechanism_list = {'iGABABseed'};
    sim_spec.connections(i).parameters = {'gGABAB',0.8,'EGABAB',-95,...
        'tauGABABd',150,'tauGABABr',38,... 'gGABAB_hetero',gsyn_hetero, ...
        'TmaxGABAB',0.5 ...
        };

%% Running simulation.

% vary = {'deepRS', 'I_app', [-7 -10];
%     'deepRS->RS', 'gNMDA', [0 5]};

Today = datestr(datenum(date),'yy-mm-dd');
Now = clock;
name = sprintf('GABABseed_error_%s_%g_%g_%.4g', Today, Now(4), Now(5), Now(6));

if nargout == 1
    
    data = dsSimulate(sim_spec, 'tspan', [0 3000], 'dt', .01, 'downsample_factor', 10, 'solver', 'rk4', 'coder', 0,...
        'random_seed', 2,'verbose_flag', 1, 'cluster_flag', 0, 'debug_flag', 1, 'compile_flag', compile_flag,...
        'overwrite_flag', 1, 'save_data_flag', 1, 'study_dir', name);
    
    varargout{1} = data;
    
else
    
    dsSimulate(sim_spec, 'tspan', [0 3000], 'dt', .01, 'downsample_factor', 10, 'solver', 'rk4', 'coder', 0,...
        'random_seed', 2,'verbose_flag', 1, 'cluster_flag', cluster_flag, 'debug_flag', 1, 'compile_flag', compile_flag,...
        'overwrite_flag', 1, 'one_solve_file_flag', 0, 'qsub_mode', 'array',...
        'save_data_flag', 1, 'study_dir', name);
    
end
    
end