function synapse_direction_error(cluster_flag, compile_flag)

if nargin < 2, compile_flag = []; end
if isempty(compile_flag), compile_flag = 0; end
if nargin < 1, cluster_flag = []; end
if isempty(cluster_flag), cluster_flag = 1; end

%% Defining sim_spec.

sim_spec = struct();

i=1;
sim_spec.populations(i).name = 'RS';
sim_spec.populations(i).size = 5;
sim_spec.populations(i).equations = {['V''=@current/Cm; V(0)=' num2str(-65) '; monitor functions; monitor V.spikes(0);']};
sim_spec.populations(i).mechanism_list = {'IBiNaF','IBiKDR',...
%     'iPeriodicPulsesFacilitate'...
%     'IBdbiPoissonExpJason','itonicPaired','IBnoise',...
%     'IBiMMich','IBiCaH','IBleaknoisy',...
    };
sim_spec.populations(i).parameters = {'V_IC', -65, 'Cm', 0.9};
% sim_spec.populations(i).parameters = {...
%     'V_IC',-65,'IC_noise',0.25,'Cm',0.9, 'E_l',-67,'E_l_std',0,'g_l',0.1,...
%     'PPstim', 0, 'PPfreq', 4, 'PPwidth', 2, 'PPshift', 0, 'PPonset', 10,...
%     'PPoffset', 3000, 'ap_pulse_num', 0, 'ap_pulse_delay', 0, 'pulse_train_preset', 0,...
%     'kernel_type', 2, 'width2_rise', 0.75, 'PPFacTau', 200, 'PPFacFactor', 1,...
%     'gRAN', 0.005, 'ERAN', 0, 'tauRAN', 2, 'lambda', 1000,...
%     'stim', 5, 'onset', 0, 'offset', 0, 'stim2', 0, 'onset2', 0, 'offset2', Inf,...
%     'V_noise', 0.3,...
%     'gNaF', 100, 'E_NaF', 50,...
%     'gKDR', 80, 'E_KDR', -95,...
%     'gM', 0.5, 'E_M', -95,...
%     'gCaH', 0, 'E_CaH', 125,...
%     };

i=i+1;
sim_spec.populations(i).name = 'deepRS';
sim_spec.populations(i).size = 1;
sim_spec.populations(i).equations = {['V''=(@current)/Cm; V(0)=' num2str(-65) '; monitor functions; monitor V.spikes(0);']};
sim_spec.populations(i).mechanism_list = {'iKDRG','iNaG','itonicBen'...
%     'iNaP','iKs','iKsConst','iLeak',...
%     'CaDynT','iCaTraub','iKCaT','iPeriodicPulsesBen',...
    };
sim_spec.populations(i).parameters = {'Cm', 2.7};
% sim_spec.populations(i).parameters = {...
%     'Cm', 2.7,  'PPstim', 0, 'gSpike', 0, 'PPcenter', 0, 'PPnorm', 0,...
%     'gKs', 1.4472, 'gKCs', 0, 'gNaP', 0.4307, 'gKCa', 0.1512, 'bKCa', .002,...
%     'gCa', 0.54, 'CAF', 2.2222,...
%     'gl', 0.27, 'gNa', 135, 'gKDR', 54, 'tau_h', 5, 'tau_m', 5,...
%     'I_const', 0, 'ton', 500, 'toff', Inf, 'I_app', -9.8, 'Inoise', 0,...                                         %  (ton<t&t<toff) %%% 'PPstim = 0; PPfreq = 1.5; PPwidth = floor((1000/PPfreq)/4); PPshift = 0; ap_pulse_num = 0; kernel_type = 7;',... % in ms
%     'PPonset', 10, 'gCar', 0,... % 'STPstim',0, 'dsfact',dsfact,...
%     };

i=1;
sim_spec.connections(i).direction = 'deepRS->RS';
sim_spec.connections(i).mechanism_list = {'IBaIBdbiSYNseed','iNMDA'};
sim_spec.connections(i).parameters = {'g_SYN', 0.15, 'E_SYN', 0, 'tauDx', 1,...
    'tauRx', 0.25, 'fanout', Inf, 'IC_noise', 0, 'g_SYN_hetero', 0,...
    'gNMDA', 5, 'ENMDA', 0, 'tauNMDAr', 5, 'tauNMDAd', 100,...
    };

i=i+1;
sim_spec.connections(i).direction = 'RS->deepRS';
sim_spec.connections(i).mechanism_list = {'IBaIBdbiSYNseed'};
sim_spec.connections(i).parameters = {'g_SYN', 0.03, 'E_SYN', 0, 'tauDx', 1, 'tauRx', 0.25, 'fanout', Inf,...
    'IC_noise', 0, 'g_SYN_hetero', 0, ...
    };

%% Running simulation.

vary = {'deepRS', 'I_app', [-7 -10];
    'deepRS->RS', 'gNMDA', [0 5]};

Today = datestr(datenum(date),'yy-mm-dd');
Now = clock;
name = sprintf('synapse_direction_error_%s_%g_%g_%.4g', Today, Now(4), Now(5), Now(6));

dsSimulate(sim_spec, 'vary', vary, 'tspan', [0 3000], 'dt', .01, 'downsample_factor', 10, 'solver', 'rk4', 'coder', 0,...
    'random_seed', 2,'verbose_flag', 1, 'cluster_flag', cluster_flag, 'debug_flag', 1, 'compile_flag', compile_flag,...
    'overwrite_flag', 1, 'one_solve_file_flag', 1, 'qsub_mode', 'array',...
    'save_data_flag', 1, 'study_dir', name);
    
end